name: Debug workflow for LOS to staging

on:
  push:
    branches:
      - master
    paths:
      - los-test/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: delop from los-test to staging
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload files
      uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
      id: upload-files
      with:
         ontology-type: "vocabulary"
         ontology: "los"
         host: "https://staging.fellesdatakatalog.digdir.no"
         api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}
         files: |
            los-test/los/digdir-contact-point.ttl text/turtle en digdir-contact-point/digdir-contact-point.ttl
            los-test/los/digdir-contact-point-en.html text/html en digdir-contact-point/digdir-contact-point-en.html
            los-test/los/digdir-contact-point-nb.html text/html nb digdir-contact-point/digdir-contact-point-nb.html
            los-test/los/digdir-contact-point-nn.html text/html nn digdir-contact-point/digdir-contact-point-nn.html
