name: Deploy LOS to staging

on:
  push:
    branches:
      - master
    paths:
      - los-test/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: delop from los-test to staging
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload files
      uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
      id: upload-files
      with:
         ontology-type: "vocabulary"
         ontology: "los"
         host: "https://staging.fellesdatakatalog.digdir.no"
         api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}
         files: |
            los-test/LOS-en.html text/html en
            los-test/LOS-nb.html text/html nb
            los-test/LOS-nn.html text/html nn
            los-test/LOS.ttl text/turtle en
            los-test/los/digdir-contact-point.ttl text/turtle en digdir-contact-point/digdir-contact-point.ttl
            los-test/los/digdir-contact-point-en.html text/html en digdir-contact-point/digdir-contact-point-en.html
            los-test/los/digdir-contact-point-nb.html text/html nb digdir-contact-point/digdir-contact-point-nb.html
            los-test/los/digdir-contact-point-nn.html text/html nn digdir-contact-point/digdir-contact-point-nn.html
            los-test/los/loslev1.ttl text/turtle en loslev1/loslev1.ttl
            los-test/los/loslev1-en.html text/html en loslev1/loslev1-en.html
            los-test/los/loslev1-nb.html text/html nb loslev1/loslev1-nb.html
            los-test/los/loslev1-nn.html text/html nn loslev1/dloslev1-nn.html
            los-test/los/loslev2.ttl text/turtle en loslev2/loslev2.ttl
            los-test/los/loslev2-en.html text/html en loslev2/loslev2-en.html
            los-test/los/loslev2-nb.html text/html nb loslev2/loslev2-nb.html
            los-test/los/loslev2-nn.html text/html nn loslev2/loslev2-nn.html
            los-test/los/loslev3.ttl text/turtle en loslev3/loslev3.ttl
            los-test/los/loslev3-en.html text/html en loslev3/loslev3-en.html
            los-test/los/loslev3-nb.html text/html nb loslev3/loslev3-nb.html
            los-test/los/loslev3-nn.html text/html nn loslev3/loslev3-nn.html
            los-test/los/los10001.ttl text/turtle en los10001/los10001.ttl
            los-test/los/los10001-en.html text/html en los10001/los10001-en.html
            los-test/los/los10001-nb.html text/html nb los10001/los10001-nb.html
            los-test/los/los10001-nn.html text/html nn los10001/los10001-nn.html
            los-test/los/los10002.ttl text/turtle en los10002/los10002.ttl
            los-test/los/los10002-en.html text/html en los10002/los10002-en.html
            los-test/los/los10002-nb.html text/html nb los10002/los10002-nb.html
            los-test/los/los10002-nn.html text/html nn los10002/los10002-nn.html
            los-test/los/los10003.ttl text/turtle en los10003/los10003.ttl
            los-test/los/los10003-en.html text/html en los10003/los10003-en.html
            los-test/los/los10003-nb.html text/html nb los10003/los10003-nb.html
            los-test/los/los10003-nn.html text/html nn los10003/los10003-nn.html
            los-test/los/los20001.ttl text/turtle en los20001/los20001.ttl
            los-test/los/los20001-en.html text/html en los20001/los20001-en.html
            los-test/los/los20001-nb.html text/html nb los20001/los20001-nb.html
            los-test/los/los20001-nn.html text/html nn los20001/los20001-nn.html
            los-test/los/los20002.ttl text/turtle en los20002/los20002.ttl
            los-test/los/los20002-en.html text/html en los20002/los20002-en.html
            los-test/los/los20002-nb.html text/html nb los20002/los20002-nb.html
            los-test/los/los20002-nn.html text/html nn los20002/los20002-nn.html
            los-test/los/los30001.ttl text/turtle en los30001/los30001.ttl
            los-test/los/los30001-en.html text/html en los30001/los30001-en.html
            los-test/los/los30001-nb.html text/html nb los30001/los30001-nb.html
            los-test/los/los30001-nn.html text/html nn los30001/los30001-nn.html
            